name: Update Conda-Forge Recipe

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-conda-forge:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: 0.1.2 #${{ github.event.release.tag_name }}
      YAML_PATH: recipe/meta.yaml
      PACKAGE_NAME: hpc
      ORG_NAME: Serapieum-of-alex

    steps:
      - name: Checkout the feedstock
        uses: actions/checkout@v2
        with:
          repository: conda-forge/hpc-feedstock
          token: ${{ secrets.CREATE_RELEASE }}

      - name: Update recipe version and sha256
        run: |
          echo $TAG_NAME
          # Assuming a simple Python package, update the version
          sed -i "s/version = \".*\"/version = \"$TAG_NAME\"/" $YAML_PATH
          # Update the sha256 checksum (you would need to calculate this, e.g., by downloading the release source archive)
          SHA256SUM=$(wget -qO- $URL | sha256sum | cut -d ' ' -f1)
          sed -i "s/sha256: .*/sha256: $SHA256SUM/" $YAML_PATH
        env:
            URL: https://github.com/$ORG_NAME/$PACKAGE_NAME/archive/$TAG_NAME.tar.gz

      - name: Download requirements.txt
        run: |
          # Download the requirements.txt from the repository to the feedstock repository
          curl -sL "https://raw.githubusercontent.com/$ORG_NAME/$PACKAGE_NAME/$TAG_NAME/requirements.txt" -o requirements.txt

          # Prepare the requirements to be inserted into the meta.yaml
          # Prefix each line with two spaces and a dash
          formatted_requirements=$(sed 's/^/    - /' requirements.txt)
          echo "copied packages ------------------"
          echo "$formatted_requirements"

          # Delete the existing 'requirements: run:' section from meta.yaml
          sed -i.bak '/  run:/,/^[^ ]/{
                /  run:/b
                /test:/b
                d
            }' $YAML_PATH
          cat $YAML_PATH
          echo "-----------------------------------------------------------------------"
          # Now, we need to add the new requirements back into meta.yaml
          # We'll use awk to do this, looking for the line just before where we want to insert the new requirements
          awk -v req="$formatted_requirements" '
              $1=="run:" {
                  print "  run:";  # Print the "run:" line
                  print req;  # Print the new requirements
                  skip = 1;
                  next;  # Skip to the next line
              }
              /^[^ ]/ { skip = 0 }  # Reset skip flag on encountering a non-indented line
              skip { next }  # Skip lines until skip flag is reset
              { print }  # Print all other lines
          ' $YAML_PATH > temp_meta.yaml && mv temp_meta.yaml $YAML_PATH

          echo "---------------------------"
          cat $YAML_PATH

      - name: Configure Git
        run: |
          git config --global user.name "mafarrag"
          git config credential.username "mafarrag"
          git config --global credential.useHttpPath true
          git config --global user.email "moah.farag@gmail.com"

      - name: Commit changes
        run: |
          cat $YAML_PATH
          git add $YAML_PATH
          git commit -m "Update to version $TAG_NAME"
          echo "---------------------------"
          git push
        env:
          token: ${{ secrets.CREATE_RELEASE }}

      # If you want to create a pull request to the feedstock repository
      - name: Create Pull Request
        run: |
          echo $TAG_NAME
          git checkout -b version-update-$TAG_NAME
          git push origin version-update-$TAG_NAME
          gh pr create --title "Update recipe to $TAG_NAME" --body "This PR updates the recipe to the newly released version." --head version-update-$TAG_NAME --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
