name: pypi-deployment
on: [push]

jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py install

      - name: Generate coverage report
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          python -m pytest -vvv --cov=hpc --cov-report=xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
