name: tests
on: [push]

jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-key: pixi-${{ hashFiles('pixi.lock') }}
          # only write caches on main to save space
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run tests
        run: pixi run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
