name: tests
on: [push]

jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.24.2
#           cache: true

      - name: Install dependencies
        run: pixi install --locked

      - name: Run tests
        run: pixi run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
