name: tests
on: [push]

jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        environment: [py311, py312]

    steps:
      - uses: actions/checkout@v4
      - name: Environment ${{ matrix.environment }} ${{ matrix.os }}
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          environments: ${{ matrix.environment }}
          pixi-version: v0.49.0
          cache: true
          cache-key: pixi-${{ hashFiles('pixi.lock') }}
          # only write caches on main to save space
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run tests
        run: pixi run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
